version: '3.8'

services:
  postgres:
    image: postgres:13.10
    restart: always
    environment:
      POSTGRES_DB: tqs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tqs_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    command: ["./mvnw", "spring-boot:run"]
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
