package hello.world;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;

public class IpmaTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ipma() {
    driver.get("https://www.ipma.pt/pt/otempo/prev.localidade.hora/#Aveiro&Aveiro");
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));
    System.out.println(driver.findElement(By.xpath("//div[3]/div/div[3]")).getText());
    System.out.println(driver.findElement(By.xpath("//div[2]/div[3]")).getText());
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[4]/div[3]")));
    System.out.println(driver.findElement(By.xpath("//div[4]/div[3]")).getText());
  }
}
