package hello.world;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class IpmaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ipma() {
    driver.get("https://www.ipma.pt/pt/otempo/prev.localidade.hora/#Aveiro&Aveiro");
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));
    System.out.println(1111111111111L);
    System.out.println(driver.findElement(By.xpath("//div[3]/div/div[3]")).getText());
    System.out.println(driver.findElement(By.xpath("//div[2]/div[3]")).getText());
    System.out.println(driver.findElement(By.xpath("//div[4]/div[3]")).getText());
    System.out.println(1111111111111L);
  }
}
