package hello.world;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class Teste1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @org.junit.jupiter.api.Test
  public void teste1() throws InterruptedException {
    driver.get("https://www.ua.pt/pt/departamentos-escolas");
    driver.wait(5000); 
    driver.manage().window().setSize(new Dimension(1550, 830));
    driver.wait(5000);
    driver.findElement(By.linkText("Eletrónica, Telecomunicações e Informática")).click();
    driver.wait(5000);
    js.executeScript("window.scrollTo(0,0)");
    driver.wait(5000);
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/section[2]/div[2]/div/div[13]/div/a/div/p")).click();
    driver.wait(5000);
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/section/div/div[2]/div[2]/div[2]/button")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
